# Generated by Django 5.1.12 on 2026-09-07 06:01

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='confirmed_by',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replaces',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Set on the corrected invoice, pointing back at the voided original (PRD §14).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_rep',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_by',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='warehouse',
            field=auto_prefetch.ForeignKey(help_text='Warehouse stock is deducted from on confirmation.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('organization', 'email')},
        ),
    ]
