# Generated by Django 5.1.12 on 2026-10-07 06:28

import core.helper.media
import core.helper.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(help_text='The actual template file (e.g. HTML, DOCX).', max_length=255, storage=core.helper.storage.RawCloudinaryStorage(), upload_to=core.helper.media.MediaHelper.get_template_upload_path),
        ),
    ]
