# Generated by Django 5.1.12 on 2026-10-01 21:50

from django.db import migrations

from core.applications.invoice.seeding import seed_default_templates


def seed(apps, schema_editor):
    DocumentTemplate = apps.get_model("invoice", "DocumentTemplate")
    seed_default_templates(DocumentTemplate)


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed,
            migrations.RunPython.noop,
        ),
    ]