# Generated by Django 5.1.12 on 2026-09-18 19:56

import auto_prefetch
import core.helper.media
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('quote', 'Quote'), ('credit_note', 'Credit Note')], max_length=20)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('padding', models.PositiveIntegerField(default=6)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('organization', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='users.organization')),
            ],
            options={
                'verbose_name': 'Document Sequence',
                'verbose_name_plural': 'Document Sequences',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'constraints': [models.UniqueConstraint(fields=('organization', 'document_type'), name='unique_sequence_per_org_and_type')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('quote', 'Quote'), ('credit_note', 'Credit Note')], default='invoice', max_length=20, verbose_name='Template Type')),
                ('file', models.FileField(help_text='The actual template file (e.g. HTML, DOCX).', upload_to=core.helper.media.MediaHelper.get_template_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', auto_prefetch.ForeignKey(blank=True, help_text='Owning organization for a Custom template. Null for Default/System templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='users.organization')),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_template_name_per_org')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
