# Generated by Django 5.1.12 on 2026-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_documentsequence_documenttemplate'),
        ('users', '0003_businesstype_remove_planfeature_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='The shared default for its type. Only valid when organization is null.'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('organization__isnull', True)), fields=('template_type',), name='unique_default_template_per_type'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('organization__isnull', True), _connector='OR'), name='default_template_is_shared'),
        ),
    ]
