# Generated by Django 5.1.12 on 2026-10-03 14:39

import auto_prefetch
import core.helper.media
import core.helper.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_seed_default_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.FileField(help_text='The actual template file (e.g. HTML, DOCX).', storage=core.helper.storage.RawCloudinaryStorage(), upload_to=core.helper.media.MediaHelper.get_template_upload_path),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='voided_by',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to={'memberships__role__slug': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
