# Generated by Django 5.1.12 on <date>

from django.db import migrations

from core.applications.invoice.seeding import seed_default_templates


def seed(apps, schema_editor):
    # The historical model, so this migration never depends on today's model code.
    DocumentTemplate = apps.get_model("invoice", "DocumentTemplate")
    seed_default_templates(DocumentTemplate)


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_documenttemplate_is_default_and_more"),   # use the exact name from your listing
    ]

    operations = [
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]