# Generated by Django 5.1.12 on 2026-10-03 16:11

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_seed_default_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='voided_by',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to={'memberships__role__slug': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
