# Generated by Django 5.1.12 on 2026-10-01 20:03

import core.helper.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, editable=False, help_text='Current on-hand quantity. System-maintained — see InventoryLedgerEntry.')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_moved', models.IntegerField(help_text='Positive for stock coming in, negative for stock going out.')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost basis per unit at the time of movement, useful for COGS calculation.', max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Ledger Entry',
                'verbose_name_plural': 'Inventory Ledger Entries',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalStockCount',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_date', models.DateField(help_text='Date the physical count was carried out.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', help_text='DRAFT while counting is in progress; COMPLETED once finalized.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any general notes about this count session.', null=True)),
            ],
            options={
                'verbose_name': 'Physical Stock Count',
                'verbose_name_plural': 'Physical Stock Counts',
                'ordering': ['-count_date'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalStockCountItem',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.IntegerField(help_text='Snapshot of Inventory.quantity at the moment counting started.')),
                ('counted_quantity', models.IntegerField(help_text='Quantity physically counted on the warehouse floor.')),
                ('variance_reason', models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('missing', 'Missing'), ('wrong_entry', 'Wrong Entry'), ('unrecorded_return', 'Unrecorded Return'), ('warehouse_error', 'Warehouse Error'), ('other', 'Other')], help_text='Required when counted_quantity differs from expected_quantity.', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional detail on the variance, if any.', null=True)),
            ],
            options={
                'verbose_name': 'Physical Stock Count Item',
                'verbose_name_plural': 'Physical Stock Count Items',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustmentRequest',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_quantity_change', models.IntegerField(help_text='Signed: positive to add stock, negative to remove.')),
                ('reason', models.TextField(help_text='Why this adjustment is being requested.')),
                ('status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval state — only APPROVED requests result in a stock movement.', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this request was approved or rejected.', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required explanation when the request is rejected.', null=True)),
            ],
            options={
                'verbose_name': 'Stock Adjustment Request',
                'verbose_name_plural': 'Stock Adjustment Requests',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
