# Generated by Django 5.1.12 on 2026-10-04 12:54

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='batch',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Specific batch of the product, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.productbatch'),
        ),
    ]
