# Generated by Django 5.1.12 on 2026-09-07 06:01

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        ('products', '0002_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Specific shelf/rack this stock is placed at, if tracked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='warehouse.stocklocation'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=auto_prefetch.ForeignKey(help_text='Product this stock level is for.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=auto_prefetch.ForeignKey(help_text='Warehouse this stock level applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='content_type',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Model type of the record that caused this movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='performed_by',
            field=auto_prefetch.ForeignKey(help_text='User whose action triggered this movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='product',
            field=auto_prefetch.ForeignKey(help_text='Product this movement affects.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='warehouse',
            field=auto_prefetch.ForeignKey(help_text='Warehouse this movement occurred in.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='physicalstockcount',
            name='counted_by',
            field=auto_prefetch.ForeignKey(help_text='User who performed the physical count.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalstockcount',
            name='warehouse',
            field=auto_prefetch.ForeignKey(help_text='Warehouse being counted.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='physicalstockcountitem',
            name='count',
            field=auto_prefetch.ForeignKey(help_text='The count session this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.physicalstockcount'),
        ),
        migrations.AddField(
            model_name='physicalstockcountitem',
            name='product',
            field=auto_prefetch.ForeignKey(help_text='Product being counted.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='product',
            field=auto_prefetch.ForeignKey(help_text='Product the adjustment applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='requested_by',
            field=auto_prefetch.ForeignKey(help_text='User who raised this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_stock_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='reviewed_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Admin/Owner who approved or rejected this request.', limit_choices_to=models.Q(('role__in', ['owner', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stock_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='warehouse',
            field=auto_prefetch.ForeignKey(help_text='Warehouse the adjustment applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='warehouse.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_i_product_f6b65e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_i_product_43bc16_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='inventory_i_content_b7c0e9_idx'),
        ),
    ]
