# Generated by Django 5.1.12 on 2026-09-14 04:34

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_initial'),
        ('products', '0003_product_product_type_product_tax_config_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_product_f6b65e_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_product_43bc16_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Specific variant of the product, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Variant this movement affects, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='physicalstockcountitem',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Variant being counted, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_items', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Variant the adjustment applies to, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='products.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'variant', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'variant', 'warehouse'], name='inventory_i_product_f3f507_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'variant', 'warehouse'], name='inventory_i_product_c312d5_idx'),
        ),
    ]
