# Generated by Django 5.1.12 on 2026-10-04 12:54

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('products', '0001_initial'),
        ('transactions', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Specific shelf/rack this stock is placed at, if tracked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='warehouse.stocklocation'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=auto_prefetch.ForeignKey(help_text='Product this stock level is for.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Specific variant of the product, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=auto_prefetch.ForeignKey(help_text='Warehouse this stock level applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryledgerentry',
            name='batch',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Optional specific batch involved in the movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='products.productbatch'),
        ),
        migrations.AddField(
            model_name='inventoryledgerentry',
            name='product',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventoryledgerentry',
            name='transaction',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='inventoryledgerentry',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Optional specific variant involved in the movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='inventoryledgerentry',
            name='warehouse',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='physicalstockcount',
            name='counted_by',
            field=auto_prefetch.ForeignKey(help_text='User who performed the physical count.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicalstockcount',
            name='warehouse',
            field=auto_prefetch.ForeignKey(help_text='Warehouse being counted.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='physicalstockcountitem',
            name='count',
            field=auto_prefetch.ForeignKey(help_text='The count session this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.physicalstockcount'),
        ),
        migrations.AddField(
            model_name='physicalstockcountitem',
            name='product',
            field=auto_prefetch.ForeignKey(help_text='Product being counted.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='physicalstockcountitem',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Variant being counted, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_items', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='batch',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Batch the adjustment applies to, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='products.productbatch'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='product',
            field=auto_prefetch.ForeignKey(help_text='Product the adjustment applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='requested_by',
            field=auto_prefetch.ForeignKey(help_text='User who raised this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_stock_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='reviewed_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Admin/Owner who approved or rejected this request.', limit_choices_to=models.Q(('memberships__role__slug__in', ['owner', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stock_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Variant the adjustment applies to, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='warehouse',
            field=auto_prefetch.ForeignKey(help_text='Warehouse the adjustment applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='warehouse.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'variant', 'batch', 'warehouse'], name='inventory_i_product_6ad4c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'variant', 'batch', 'warehouse')},
        ),
    ]
