# Generated by Django 5.1.12 on 2026-09-15 02:34

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_inventory_i_product_f6b65e_idx_and_more'),
        ('products', '0003_product_product_type_product_tax_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Current on-hand quantity. System-maintained — see InventoryLedgerEntry.'),
        ),
        migrations.CreateModel(
            name='InventoryLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_moved', models.IntegerField(help_text='Positive for stock coming in, negative for stock going out.')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost basis per unit at the time of movement, useful for COGS calculation.', max_digits=12, null=True)),
                ('product', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory Ledger Entry',
                'verbose_name_plural': 'Inventory Ledger Entries',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
