# Generated by Django 5.1.12 on 2026-10-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustmentrequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('missing', 'Missing'), ('wrong_entry', 'Wrong Entry'), ('unrecorded_return', 'Unrecorded Return'), ('warehouse_error', 'Warehouse Error'), ('other', 'Other')], help_text='Standardized reason for this adjustment.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional note for this adjustment.', null=True),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='requested_unit',
            field=models.CharField(blank=True, help_text="The unit selected by the user in the UI (e.g. 'Bottle').", max_length=50, null=True),
        ),
    ]
