# Generated by Django 5.1.12 on 2026-09-15 02:34

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventorytransaction_content_type_and_more'),
        ('products', '0003_product_product_type_product_tax_config_and_more'),
        ('transactions', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryledgerentry',
            name='transaction',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='inventoryledgerentry',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Optional specific variant involved in the movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='inventoryledgerentry',
            name='warehouse',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='warehouse.warehouse'),
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
    ]
