# Generated by Django 5.1.12 on 2026-10-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stockadjustmentrequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, editable=False, help_text='Current on-hand quantity. System-maintained — see InventoryLedgerEntry.'),
        ),
    ]
