# Generated by Django 5.1.12 on 2026-10-03 16:11

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryledgerentry_transaction_and_more'),
        ('products', '0004_remove_product_current_stock_remove_product_image_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_product_f3f507_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Specific batch of the product, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.productbatch'),
        ),
        migrations.AddField(
            model_name='inventoryledgerentry',
            name='batch',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Optional specific batch involved in the movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='products.productbatch'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='batch',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Batch the adjustment applies to, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='products.productbatch'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentrequest',
            name='reviewed_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Admin/Owner who approved or rejected this request.', limit_choices_to=models.Q(('memberships__role__slug__in', ['owner', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stock_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'variant', 'batch', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'variant', 'batch', 'warehouse'], name='inventory_i_product_6ad4c1_idx'),
        ),
    ]
