# Generated by Django 5.1.12 on 2026-10-03 14:39

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_inventory_i_product_f3f507_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustmentrequest',
            name='reviewed_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Admin/Owner who approved or rejected this request.', limit_choices_to=models.Q(('memberships__role__slug__in', ['owner', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stock_adjustments', to=settings.AUTH_USER_MODEL),
        ),
    ]
