# Generated by Django 5.1.12 on 2026-09-07 06:01

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Port Harcourt Main Warehouse'.", max_length=150, verbose_name='Warehouse Name')),
                ('code', models.CharField(db_index=True, help_text="Short unique code used in references and reports, e.g. 'PH-01'.", max_length=30, verbose_name='Warehouse Code')),
                ('address', models.TextField(blank=True, help_text='Physical address of the warehouse.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive warehouses are hidden from new-purchase/invoice pickers.')),
                ('manager', auto_prefetch.ForeignKey(blank=True, help_text="User responsible for this warehouse's day-to-day operations.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
                ('organization', auto_prefetch.ForeignKey(help_text='Organization this warehouse belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='users.organization')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('organization', 'code')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Aisle 3, Shelf B'.", max_length=100, verbose_name='Location Name')),
                ('description', models.TextField(blank=True, help_text="Optional notes on what's stored here or how to find it.", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive locations are hidden from stock-placement pickers.')),
                ('warehouse', auto_prefetch.ForeignKey(help_text='Warehouse this shelf/rack/bin is inside.', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Location',
                'verbose_name_plural': 'Stock Locations',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('warehouse', 'name')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
