# Generated by Django 5.1.12 on 2026-10-01 20:03

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('sales', '0002_initial'),
        ('users', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='location',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='warehouse.stocklocation'),
        ),
        migrations.AddField(
            model_name='sale',
            name='organization',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.organization'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_rep',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='organization',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='original_sale',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='salereturnitem',
            name='sale_item',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem'),
        ),
        migrations.AddField(
            model_name='salereturnitem',
            name='sale_return',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salereturn'),
        ),
    ]
