# Generated by Django 5.1.12 on 2026-10-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_multiplier',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_name',
            field=models.CharField(choices=[('pcs', 'Piece(s)'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('box', 'Box'), ('pack', 'Pack'), ('carton', 'Carton'), ('dozen', 'Dozen'), ('m', 'Metre'), ('other', 'Other')], default='pcs', max_length=10),
        ),
    ]
