services:
  docs:
    image: riinox-backend_local_docs
    container_name: riinox-backend_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./riinox-backend:/app/riinox-backend:z
    ports:
      - "9000:9000"
    command: /start-docs
