# Generated by Django 5.1.12 on 2026-09-07 06:01

import core.helper.media
import core.helper.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Manufacturer or brand name, e.g. 'Dangote'.", max_length=150, verbose_name='Brand Name')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive brands are hidden from product-creation pickers.')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name of the category, e.g. 'Beverages'.", max_length=150, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Optional longer description of what belongs in this category.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden from product-creation pickers.')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Customer-facing product name.', max_length=255, verbose_name='Product Name')),
                ('sku', models.CharField(db_index=True, help_text='Internal stock-keeping unit code, unique within the organization.', max_length=100, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Scannable barcode or QR payload used for quick lookup (PRD §35).', max_length=100, null=True, verbose_name='Barcode / QR Code')),
                ('description', models.TextField(blank=True, help_text='Longer product description shown to staff and customers.', null=True)),
                ('quality_grade', models.CharField(blank=True, help_text="Free-form product quality/grade label, e.g. 'Grade A'.", max_length=50, null=True)),
                ('unit_of_measurement', models.CharField(choices=[('pcs', 'Piece(s)'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('box', 'Box'), ('pack', 'Pack'), ('carton', 'Carton'), ('dozen', 'Dozen'), ('m', 'Metre'), ('other', 'Other')], default='pcs', help_text='Unit stock quantities for this product are counted in.', max_length=10)),
                ('image', models.FileField(blank=True, help_text='Primary product image shown in catalogues and barcode lookups.', null=True, upload_to=core.helper.media.MediaHelper.get_image_upload_path)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, help_text='Admin-only. What the business pays the vendor per unit.', max_digits=12, verbose_name='Purchase Cost')),
                ('vendor_sale_cost', models.DecimalField(decimal_places=2, default=0, help_text='Admin-only. Cost basis used for vendor-facing terms.', max_digits=12, verbose_name='Vendor Sale Cost')),
                ('customer_sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Price charged to customers. Visible to Staff but not editable by them.', max_digits=12, verbose_name='Customer Sale Price')),
                ('minimum_stock_level', models.PositiveIntegerField(default=0, help_text='Triggers LOW_STOCK notifications when on-hand quantity reaches this.')),
                ('opening_stock', models.PositiveIntegerField(default=0, help_text='Stock quantity recorded when the product was first created.')),
                ('current_stock', models.PositiveIntegerField(default=0, editable=False, help_text='Denormalized read cache summed across all warehouses. Source of truth is InventoryTransaction — do not edit directly.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued'), ('archived', 'Archived')], default='active', help_text='Lifecycle status. Archived/discontinued products stay visible in historical records.', max_length=20)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
