# Generated by Django 5.1.12 on 2026-09-07 06:01

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='organization',
            field=auto_prefetch.ForeignKey(help_text='Organization this brand belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='users.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=auto_prefetch.ForeignKey(help_text='Organization this category belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='users.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Manufacturer/brand of this product, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Category this product is grouped under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Admin/Owner who created this product record (PRD §6: Admin-only creation).', limit_choices_to=models.Q(('role__in', ['owner', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=auto_prefetch.ForeignKey(help_text='Organization this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'sku')},
        ),
    ]
