# Generated by Django 5.1.12 on 2026-09-14 04:34

import auto_prefetch
import core.helper.media
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('service', 'Service'), ('digital', 'Digital'), ('bundle', 'Bundle'), ('consumable', 'Consumable'), ('non_stock', 'Non-Stock')], default='physical', help_text='Type of product (e.g., Physical, Service, Digital).', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_config',
            field=models.CharField(choices=[('taxable', 'Taxable'), ('non_taxable', 'Non-Taxable'), ('exempt', 'Exempt')], default='taxable', help_text='Tax configuration for this product.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Specific percentage tax rate override, if applicable.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='Whether to enforce inventory ledger tracking for this product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to=models.Q(('memberships__role__in', ['owner', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=core.helper.media.MediaHelper.get_image_upload_path)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image for the product.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls the display order of product images.')),
                ('product', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['sort_order', '-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Name/description of this variant (e.g. 'Red / Large').", max_length=255, verbose_name='Variant Name')),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Optional specific SKU for this variant.', max_length=100, null=True, verbose_name='Variant SKU')),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Optional specific barcode for this variant.', max_length=100, null=True, verbose_name='Variant Barcode / QR Code')),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Admin-only. Override what the business pays the vendor per unit.', max_digits=12, null=True, verbose_name='Purchase Cost Override')),
                ('customer_sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Override the price charged to customers for this specific variant.', max_digits=12, null=True, verbose_name='Customer Sale Price Override')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this variant is active and available.')),
                ('product', auto_prefetch.ForeignKey(help_text='Product this variant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('product', 'sku')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
