# Generated by Django 5.1.12 on 2026-10-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alert_unit',
            field=models.CharField(blank=True, choices=[('pcs', 'Piece(s)'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('box', 'Box'), ('pack', 'Pack'), ('carton', 'Carton'), ('dozen', 'Dozen'), ('m', 'Metre'), ('other', 'Other')], help_text="The unit for the low stock alert (e.g. 'carton'). If not set, defaults to base unit.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='track_batches',
            field=models.BooleanField(default=False, help_text='Whether to enforce batch tracking requirements for this product.'),
        ),
    ]
