# Generated by Django 5.1.12 on 2026-10-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_type_product_tax_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_stock',
        ),
    ]
