# Generated by Django 5.1.12 on 2026-10-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_low_stock_alert_unit_product_track_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunitconversion',
            name='unit_name',
            field=models.CharField(choices=[('pcs', 'Piece(s)'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('box', 'Box'), ('pack', 'Pack'), ('carton', 'Carton'), ('dozen', 'Dozen'), ('m', 'Metre'), ('other', 'Other')], help_text="Name of the alternative unit, e.g. 'carton'.", max_length=10),
        ),
    ]
