# Generated by Django 5.1.12 on 2026-10-02 00:44

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_current_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductBulkDiscount',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum number of items required to trigger this discount.')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Fixed discount amount applied.', max_digits=12)),
                ('product', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_discounts', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Bulk Discount',
                'verbose_name_plural': 'Product Bulk Discounts',
                'ordering': ['min_quantity'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(blank=True, db_index=True, help_text='Identifier for the batch. Auto-generated if left blank.', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Optional expiry date for this batch.', null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional batch-specific cost price.', max_digits=12, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional batch-specific selling price.', max_digits=12, null=True)),
                ('product', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Batch',
                'verbose_name_plural': 'Product Batches',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('product', 'batch_number')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnitConversion',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_name', models.CharField(help_text="Name of the alternative unit, e.g. 'Carton'.", max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=3, help_text='Multiplier against the base unit. E.g. if base is Pieces and unit is Carton of 12, multiplier is 12.', max_digits=10)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional specific selling price for this unit, overriding the multiplier math.', max_digits=12, null=True)),
                ('product', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Unit Conversion',
                'verbose_name_plural': 'Product Unit Conversions',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('product', 'unit_name')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
