# Generated by Django 5.1.12 on 2026-10-03 14:39

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_productbulkdiscount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to=models.Q(('memberships__role__slug__in', ['owner', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
