class AuditAction:
    """Dotted `domain.event` codes. Each app adds its own here."""
    ORGANIZATION_CREATED = "organization.created"
    ORGANIZATION_UPDATED = "organization.updated"
    ORGANIZATION_DELETED = "organization.deleted"
    INVITATION_CREATED = "invitation.created"
    INVITATION_RESENT = "invitation.resent"
    INVITATION_REVOKED = "invitation.revoked"
    INVITATION_ACCEPTED = "invitation.accepted"
    MEMBERSHIP_ROLE_CHANGED = "membership.role_changed"
    MEMBERSHIP_DEACTIVATED = "membership.deactivated"
    MEMBERSHIP_REACTIVATED = "membership.reactivated"
    ROLE_PERMISSIONS_CHANGED = "role.permissions_changed"
