# Generated by Django 5.1.12 on 2026-09-07 06:01

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(help_text='Registered/trading name of the vendor.', max_length=255, verbose_name='Company Name')),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact at the vendor for order/delivery queries.', max_length=150, null=True, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, help_text='Vendor contact phone number.', max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='Vendor contact email.', max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, help_text="Vendor's registered or warehouse address.", null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Inactive vendors are hidden from new-purchase pickers.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this vendor (terms, reliability, etc.).', null=True)),
                ('organization', auto_prefetch.ForeignKey(help_text='Organization this vendor supplies.', on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='users.organization')),
                ('products_supplied', models.ManyToManyField(blank=True, help_text='Products this vendor is known to supply.', related_name='vendors', to='products.product')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['company_name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
