# Generated by Django 5.1.12 on 2026-09-07 06:01

import auto_prefetch
import core.helper.media
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('financial_summary', 'Financial Summary'), ('transaction_history', 'Transaction History'), ('revenue', 'Revenue Report'), ('outstanding', 'Outstanding Payments'), ('client', 'Client Invoice Summary'), ('inventory_summary', 'Inventory Summary'), ('stock_levels', 'Stock Levels'), ('stock_movements', 'Stock Movements'), ('sales_summary', 'Sales Summary'), ('top_products', 'Top Products'), ('customer_purchases', 'Customer Purchases'), ('audit_log', 'Audit Log Report'), ('user_activity', 'User Activity Report'), ('security_events', 'Security Events'), ('custom', 'Custom Report')], help_text='The category/type of this report (finance, inventory, sales, etc.).', max_length=50)),
                ('title', models.CharField(help_text='A short descriptive title for the report.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Detailed information about the report.', null=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Parameters used to generate this report (date range, staff, product, etc.) for reproducibility.')),
                ('file', models.FileField(blank=True, help_text='The generated report file.', null=True, upload_to=core.helper.media.MediaHelper.get_image_upload_path)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel')], default='pdf', help_text='The file format of the report.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', help_text='The current status of report generation.', max_length=20)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('void', 'Void'), ('confirm', 'Confirm'), ('approve', 'Approve'), ('reject', 'Reject'), ('adjust', 'Stock Adjustment'), ('receive', 'Goods Received'), ('count', 'Physical Count')], max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_value', models.JSONField(blank=True, help_text='Snapshot of the relevant field(s) before the change.', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Snapshot of the relevant field(s) after the change.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('content_type', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
