# Generated by Django 5.1.12 on 2026-10-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
