# Generated by Django 5.2.8 on 2025-12-04 23:12

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='users.school'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='teacher',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_rooms',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.school'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.school'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='time_slot',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='timetable.timeslot'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='schedules',
            field=models.ManyToManyField(related_name='timetables', to='timetable.classschedule'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='users.school'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('school', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('school', 'academic_class', 'day_of_week', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school', 'name', 'academic_year', 'term')},
        ),
    ]
