# Generated by Django 5.1.12 on 2026-09-07 06:01

import core.helper.media
import core.helper.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_number', models.CharField(db_index=True, editable=False, help_text="Auto-generated sequential reference, e.g. 'PO-2026-0004'.", max_length=30, unique=True)),
                ('vendor_invoice_number', models.CharField(blank=True, help_text="The vendor's own invoice/reference number for this order.", max_length=100, null=True, verbose_name='Vendor Invoice Number')),
                ('supporting_document', models.FileField(blank=True, help_text='Vendor invoice, waybill, or delivery note supporting this purchase.', null=True, upload_to=core.helper.media.MediaHelper.get_image_upload_path)),
                ('delivery_date', models.DateField(blank=True, help_text='Date the goods were or are expected to be delivered.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', help_text='Lifecycle status of this purchase order.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this purchase.', null=True)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_ordered', models.PositiveIntegerField(help_text='Quantity requested from the vendor.')),
                ('quantity_received', models.PositiveIntegerField(default=0, help_text='Quantity actually received so far. Only this enters inventory (PRD §10).')),
                ('purchase_cost', models.DecimalField(decimal_places=2, help_text='Snapshot of Product.purchase_cost at order time.', max_digits=12)),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
