# Generated by Django 5.1.12 on 2026-09-07 06:01

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('purchase', '0001_initial'),
        ('users', '0001_initial'),
        ('vendors', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ordered_by',
            field=auto_prefetch.ForeignKey(help_text='Admin/Owner who placed this order (PRD §10: Admin-only purchasing).', limit_choices_to=models.Q(('role__in', ['owner', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='organization',
            field=auto_prefetch.ForeignKey(help_text='Organization this purchase order belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.organization'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='received_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='User who physically received and checked in the goods.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=auto_prefetch.ForeignKey(help_text='Vendor this order was placed with.', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=auto_prefetch.ForeignKey(help_text='Warehouse the received goods will be stocked into.', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=auto_prefetch.ForeignKey(help_text='Product being ordered/received.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase',
            field=auto_prefetch.ForeignKey(help_text='Purchase order this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchase'),
        ),
    ]
