# Generated by Django 5.1.12 on 2026-10-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to this line item.', max_digits=12),
        ),
    ]
