# Generated by Django 5.1.12 on 2026-10-03 14:39

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='ordered_by',
            field=auto_prefetch.ForeignKey(help_text='Admin/Owner who placed this order (PRD §10: Admin-only purchasing).', limit_choices_to=models.Q(('memberships__role__slug__in', ['owner', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
