# Generated by Django 5.1.12 on 2026-10-08 04:12

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productunitconversion_unit_name'),
        ('purchase', '0003_purchaseitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_method',
            field=models.CharField(blank=True, help_text='Delivery method used for the order (e.g. Supplier Delivery).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Global discount applied to the purchase order.', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='order_date',
            field=models.DateField(blank=True, help_text='Date the order was placed.', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional costs such as delivery or handling.', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Specific unit of measurement the product is being ordered in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='products.productunitconversion'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='variant',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Specific variant of the product being ordered, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='products.productvariant'),
        ),
    ]
