# Generated by Django 5.1.12 on 2026-10-08 04:12

import auto_prefetch
import core.helper.media
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
        ('purchase', '0003_purchaseitem_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Receipt Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Remaining balance on the purchase order immediately after this payment.', max_digits=12)),
                ('supporting_document', models.FileField(blank=True, help_text='Receipt or proof of payment from the supplier.', null=True, upload_to=core.helper.media.MediaHelper.get_image_upload_path)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('payment', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payments', to='payment.payment')),
                ('purchase', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchase.purchase')),
                ('recorded_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_purchase_payments', to=settings.AUTH_USER_MODEL)),
                ('voided_by', auto_prefetch.ForeignKey(blank=True, limit_choices_to={'memberships__role__slug': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_purchase_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Payment',
                'verbose_name_plural': 'Purchase Payments',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
