import uuid
from datetime import timedelta
from typing import ClassVar

import auto_prefetch
from django.contrib.auth.models import AbstractUser
from django.db.models import CASCADE
from django.db.models import SET_NULL
from django.db.models import BooleanField
from django.db.models import CharField
from django.db.models import DateTimeField
from django.db.models import EmailField
from django.db.models import FileField
from django.db.models import ImageField
from django.db.models import Index
from django.db.models import OneToOneField
from django.db.models import TextField
from django.db.models import UUIDField
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from core.helper.enums import TEMPLATE_TYPES
from core.helper.enums import OrganizationTypeChoices
from core.helper.enums import UsersRole
from core.helper.media import MediaHelper
from core.helper.models import TimeBasedModel
from core.helper.utils import default_invite_expiry

from .managers import UserManager


class DocumentTemplate(TimeBasedModel):
    """
    Represents a document template that organizations can use for invoices,
    receipts, quotes, and credit notes. Templates define the layout and style
    of the documents generated by the system.
    """

    name = CharField(max_length=100, unique=True)
    description = TextField(blank=True, null=True)
    template_type = CharField(
        _("Template Type"),
        max_length=20,
        choices=TEMPLATE_TYPES.choices,
        default=TEMPLATE_TYPES.INVOICE,
    )
    file = FileField(
        upload_to=MediaHelper.get_template_upload_path,
        help_text=_("The actual template file (e.g. HTML, DOCX)."),
    )
    is_active = BooleanField(default=True)

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Document Template")
        verbose_name_plural = _("Document Templates")
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.template_type})"


class Organization(TimeBasedModel):
    """
    Represents a tenant in the SaaS system.
    Each organization can customize branding and document templates.
    """

    name = CharField(max_length=255)
    type = CharField(
        _("Organization Type"),
        max_length=50,
        choices=OrganizationTypeChoices.choices,
        default=OrganizationTypeChoices.BUSINESS,
    )
    domain = CharField(
        _("Custom Domain"),
        max_length=255,
        blank=True,
        null=True,
        help_text=_("Optional custom domain (e.g. acme.com)."),
    )

    plan = auto_prefetch.ForeignKey(
        "users.Plan",
        on_delete=CASCADE,
        related_name="organizations",
        default=1,
    )
    is_active = BooleanField(_("Active"), default=True)

    # Branding
    logo = ImageField(
        upload_to=MediaHelper.get_image_upload_path,
        blank=True,
        null=True,
        help_text=_("Logo to display on invoices and receipts."),
    )
    header_text = CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text=_("Custom header text (e.g. company slogan)."),
    )
    footer_text = CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text=_("Custom footer text (e.g. payment instructions)."),
    )

    # Template assignments
    invoice_template = auto_prefetch.ForeignKey(
        "users.DocumentTemplate",
        on_delete=SET_NULL,
        null=True,
        blank=True,
        related_name="invoice_organizations",
        limit_choices_to={"template_type": "invoice", "is_active": True},
        help_text=_("Selected invoice template for this organization."),
    )
    receipt_template = auto_prefetch.ForeignKey(
        "users.DocumentTemplate",
        on_delete=SET_NULL,
        null=True,
        blank=True,
        related_name="receipt_organizations",
        limit_choices_to={"template_type": "receipt", "is_active": True},
        help_text=_("Selected receipt template for this organization."),
    )

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Organization")
        verbose_name_plural = _("Organizations")
        ordering = ["name"]

    def __str__(self):
        return self.name


class Plan(TimeBasedModel):
    """
    Subscription plan for organizations.
    Each plan can define pricing and limits.
    this is easy for future updates
    """

    name = CharField(max_length=50, unique=True)
    description = TextField(blank=True, null=True)
    price = CharField(max_length=50, default="Free")
    is_active = BooleanField(default=True)

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Plan")
        verbose_name_plural = _("Plans")
        ordering = ["name"]

    def __str__(self):
        return self.name


class Feature(TimeBasedModel):
    """
    Represents a feature that can be enabled for a plan.
    Example: 'API Access', 'Unlimited Invoices', 'Priority Support'.
    """

    code = CharField(max_length=50, unique=True)  # e.g. "API_ACCESS"
    name = CharField(max_length=100)
    description = TextField(blank=True, null=True)

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Feature")
        verbose_name_plural = _("Features")
        ordering = ["name"]

    def __str__(self):
        return self.name


class PlanFeature(TimeBasedModel):
    plan = auto_prefetch.ForeignKey(
        "users.Plan",
        on_delete=CASCADE,
        related_name="plan_features",
    )
    feature = auto_prefetch.ForeignKey(
        "users.Feature",
        on_delete=CASCADE,
        related_name="feature_plans",
    )
    enabled = BooleanField(default=True)

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Plan Feature")
        verbose_name_plural = _("Plan Features")
        unique_together = ("plan", "feature")

    def __str__(self):
        return f"{self.feature.name} on {self.plan.name}"


class User(AbstractUser):
    """
    Custom user model for Invoice Management System.
    Email is used as the unique identifier instead of username.
    """

    first_name = None  # type: ignore
    last_name = None  # type: ignore
    username = None  # type: ignore

    # id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    name = CharField(_("Full Name"), max_length=255, blank=True)
    email = EmailField(_("Email Address"), unique=True, db_index=True)
    address = TextField(_("Address"), blank=True, null=True)
    is_active = BooleanField(_("Active"), default=True)
    is_verified = BooleanField(_("Verified"), default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects: ClassVar[UserManager] = UserManager()

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")
        ordering = ["-date_joined"]

    def __str__(self):
        return f"{self.name or self.email}"

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"pk": self.pk})

    @property
    def organizations(self):
        """Return all organizations the user is a member of."""
        return Organization.objects.filter(memberships__user=self)


class Membership(TimeBasedModel):
    """
    Membership ties a User to an Organization with a specific role.
    This enables multi-tenancy where users can belong to multiple orgs.
    """

    user = auto_prefetch.ForeignKey(
        "users.User",
        on_delete=CASCADE,
        related_name="memberships",
        null=True,
        blank=True,
    )
    organization = auto_prefetch.ForeignKey(
        "users.Organization",
        on_delete=CASCADE,
        related_name="memberships",
    )
    role = CharField(
        _("Role"),
        max_length=20,
        choices=UsersRole.choices,
        default=UsersRole.OWNER,
    )
    is_active = BooleanField(default=True)

    # Invitation fields
    invited_email = EmailField(
        _("Invited Email"),
        null=True,
        blank=True,
        help_text=_("The email address that received the invitation."),
    )
    invite_token = UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
        help_text=_("Unique token for invitation acceptance."),
    )
    accepted = BooleanField(
        default=False,
        help_text=_("Has the invited user accepted the invitation?"),
    )
    expires_at = DateTimeField(
        default=default_invite_expiry,
        help_text=_("Expiration datetime for the invitation."),
    )

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Membership")
        verbose_name_plural = _("Memberships")
        unique_together = ("user", "organization")
        indexes = [
            Index(fields=["organization", "role"]),
        ]

    def __str__(self):
        if self.user:
            return f"{self.user.email} in {self.organization.name} as {self.role}"
        return f"Invitation for {self.invited_email} to {self.organization.name} as {self.role}"


class OwnersProfile(TimeBasedModel):
    user = OneToOneField("users.User", on_delete=CASCADE, related_name="owner_profile")
    bio = TextField(blank=True, null=True)
    website = CharField(max_length=255, blank=True, null=True)

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Owner Profile")
        verbose_name_plural = _("Owner Profiles")


class AdminProfile(TimeBasedModel):
    user = OneToOneField("users.User", on_delete=CASCADE, related_name="admin_profile")
    department = CharField(max_length=100, blank=True, null=True)

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Admin Profile")
        verbose_name_plural = _("Admin Profiles")


class MemberProfile(TimeBasedModel):
    user = OneToOneField("users.User", on_delete=CASCADE, related_name="member_profile")
    team = CharField(max_length=100, blank=True, null=True)

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Member Profile")
        verbose_name_plural = _("Member Profiles")


class CustomerProfile(TimeBasedModel):
    user = OneToOneField(
        "users.User",
        on_delete=CASCADE,
        related_name="customer_profile",
    )
    address = TextField(blank=True, null=True)
    phone = CharField(max_length=20, blank=True, null=True)

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = _("Customer Profile")
        verbose_name_plural = _("Customer Profiles")

    def __str__(self):
        return f"Customer Profile for {self.user.email}"
