# Generated by Django 5.1.12 on 2026-10-01 20:03

import auto_prefetch
import core.applications.users.managers
import core.applications.users.models
import core.helper.media
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Stable key, e.g. 'wholesale_distribution'.", unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon key resolved by the frontend, e.g. 'shopping-basket'.", max_length=50)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='Short feature tags shown on the onboarding card.')),
                ('show_in_onboarding', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Business Type',
                'verbose_name_plural': 'Business Types',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="e.g. 'EDIT_INVENTORY'.", max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('module', models.CharField(blank=True, help_text="Module this permission belongs to, e.g. 'inventory', 'invoices'.", max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', core.applications.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Invitee name')),
                ('email', models.EmailField(max_length=254, verbose_name='Invitee email')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(core.applications.users.models.RoleOrganizationMatchMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive memberships grant nothing (suspended or removed member).')),
                ('invitation', auto_prefetch.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='users.invitation')),
                ('user', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'ordering': ['organization', '-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            bases=(core.applications.users.models.RoleOrganizationMatchMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminMembershipDetail',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_detail', to='users.membership')),
            ],
            options={
                'verbose_name': 'Admin Membership Detail',
                'verbose_name_plural': 'Admin Membership Details',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Trading name.', max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('staff_size', models.CharField(blank=True, choices=[('1-5', '1–5'), ('6-10', '6–10'), ('11-50', '11–50'), ('50+', '50+')], max_length=20, verbose_name='Number of staff')),
                ('domain', models.CharField(blank=True, help_text='Optional custom domain (e.g. acme.com).', max_length=255, null=True, verbose_name='Custom Domain')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, help_text='State/province/region of the business address.', max_length=100)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('currency', models.CharField(blank=True, help_text='ISO 4217 currency code.', max_length=3)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('logo', models.ImageField(blank=True, help_text='Logo to display on invoices and receipts.', null=True, upload_to=core.helper.media.MediaHelper.get_image_upload_path)),
                ('header_text', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal/ZIP code')),
                ('created_by', auto_prefetch.ForeignKey(blank=True, help_text='User who created this organization; becomes its Owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL)),
                ('credit_note_template', auto_prefetch.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'template_type': 'credit_note'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_organizations', to='invoice.documenttemplate')),
                ('invoice_template', auto_prefetch.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'template_type': 'invoice'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_organizations', to='invoice.documenttemplate')),
                ('quote_template', auto_prefetch.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'template_type': 'quote'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_organizations', to='invoice.documenttemplate')),
                ('receipt_template', auto_prefetch.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'template_type': 'receipt'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_organizations', to='invoice.documenttemplate')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.organization'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='organization',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationBusinessType',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('business_type', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_links', to='users.businesstype')),
                ('organization', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_business_types', to='users.organization')),
            ],
            options={
                'verbose_name': 'Organization Business Type',
                'verbose_name_plural': 'Organization Business Types',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='business_types',
            field=models.ManyToManyField(blank=True, related_name='organizations', through='users.OrganizationBusinessType', to='users.businesstype'),
        ),
        migrations.CreateModel(
            name='OwnerMembershipDetail',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_detail', to='users.membership')),
            ],
            options={
                'verbose_name': 'Owner Membership Detail',
                'verbose_name_plural': 'Owner Membership Details',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(help_text="Stable key, e.g. 'sales-representative'.", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False, help_text="True for the PRD's default roles; protects name/slug from editing.")),
                ('organization', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.organization')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['organization', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=auto_prefetch.ForeignKey(help_text='Must belong to the same organization as this membership.', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='users.role'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='users.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='users.permission')),
                ('role', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='users.RolePermission', to='users.permission'),
        ),
        migrations.CreateModel(
            name='StaffMembershipDetail',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_detail', to='users.membership')),
            ],
            options={
                'verbose_name': 'Staff Membership Detail',
                'verbose_name_plural': 'Staff Membership Details',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text="ISO 3166-2 subdivision code, e.g. 'NG-AB'.", max_length=10)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.AddConstraint(
            model_name='organizationbusinesstype',
            constraint=models.UniqueConstraint(fields=('organization', 'business_type'), name='unique_business_type_per_org'),
        ),
        migrations.AddConstraint(
            model_name='organizationbusinesstype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='unique_primary_business_type_per_org'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'role'], name='users_membe_organiz_467add_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_membership_per_user_org'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['organization', 'status'], name='users_invit_organiz_84adeb_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email'], name='users_invit_email_1b07c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'email'), name='unique_pending_invitation_per_org_email'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_role_slug_per_org'),
        ),
    ]
