# Generated by Django 5.1.12 on 2026-09-18 19:56

import auto_prefetch
import core.helper.models
import core.helper.utils
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_documentsequence_documenttemplate'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMembershipDetail',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Admin Membership Detail',
                'verbose_name_plural': 'Admin Membership Details',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerMembershipDetail',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Owner Membership Detail',
                'verbose_name_plural': 'Owner Membership Details',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="e.g. 'EDIT_INVENTORY'.", max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('module', models.CharField(blank=True, help_text="Module this permission belongs to, e.g. 'inventory', 'invoices'.", max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(help_text="Stable key, e.g. 'sales-representative'.", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False, help_text="True for the PRD's default roles; protects name/slug from editing.")),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['organization', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffMembershipDetail',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Staff Membership Detail',
                'verbose_name_plural': 'Staff Membership Details',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trialing', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='organization',
            name='invoice_template',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'template_type': 'invoice'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_organizations', to='invoice.documenttemplate'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='receipt_template',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'template_type': 'receipt'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_organizations', to='invoice.documenttemplate'),
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ownersprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['organization', '-created_at'], 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['price'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='users_membe_organiz_467add_idx',
            old_name='users_membe_organiz_cc3a0d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='planfeature',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='User who created this organization; becomes its Owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='credit_note_template',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'template_type': 'credit_note'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_organizations', to='invoice.documenttemplate'),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(blank=True, help_text='ISO 4217 currency code.', max_length=3),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='quote_template',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'template_type': 'quote'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_organizations', to='invoice.documenttemplate'),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='staff_size',
            field=models.CharField(blank=True, choices=[('1-5', '1–5'), ('6-10', '6–10'), ('11-50', '11–50'), ('50+', '50+')], max_length=20, verbose_name='Number of staff'),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, help_text='State/province/region of the business address.', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_period_days',
            field=models.PositiveIntegerField(default=30, help_text='Length of one billing cycle, in days.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_locations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_products',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_transactions_per_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expires_at',
            field=models.DateTimeField(default=core.helper.utils.default_invite_expiry),
        ),
        migrations.AlterField(
            model_name='membership',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Invited Email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='footer_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='header_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Trading name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('school', 'School'), ('business', 'Business'), ('ngo', 'Non-Profit / NGO'), ('government', 'Government'), ('other', 'Other')], default='business', max_length=50, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature'),
        ),
        migrations.AddField(
            model_name='adminmembershipdetail',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_detail', to='users.membership'),
        ),
        migrations.AddField(
            model_name='ownermembershipdetail',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_detail', to='users.membership'),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=auto_prefetch.ForeignKey(help_text='Must belong to the same organization as this membership.', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='users.role'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_membership_per_user_org'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted', False), ('invited_email__isnull', False)), fields=('organization', 'invited_email'), name='unique_pending_invite_per_org_email'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='users.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='users.RolePermission', to='users.permission'),
        ),
        migrations.AddField(
            model_name='staffmembershipdetail',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_detail', to='users.membership'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='users.plan'),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='DocumentTemplate',
        ),
        migrations.DeleteModel(
            name='MemberProfile',
        ),
        migrations.DeleteModel(
            name='OwnersProfile',
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_role_slug_per_org'),
        ),
    ]
