# Generated by Django 5.1.12 on 2026-10-01

from django.db import migrations

from core.applications.users.defaults import BUSINESS_TYPES


def seed_business_types(apps, schema_editor):
    BusinessType = apps.get_model("users", "BusinessType")

    for entry in BUSINESS_TYPES:
        BusinessType.objects.update_or_create(
            code=entry["code"],
            defaults={
                "name": entry["name"],
                "description": entry.get("description", ""),
                "icon": entry.get("icon", ""),
                "highlights": entry.get("highlights", []),
                "show_in_onboarding": entry.get("show_in_onboarding", True),
                "is_active": entry.get("is_active", True),
                "sort_order": entry.get("sort_order", 0),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_business_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]