# Generated by Django 5.1.12 on 2026-09-20 16:27

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminmembershipdetail_ownermembershipdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Stable key, e.g. 'wholesale_distribution'.", unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon key resolved by the frontend, e.g. 'shopping-basket'.", max_length=50)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='Short feature tags shown on the onboarding card.')),
                ('show_in_onboarding', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Business Type',
                'verbose_name_plural': 'Business Types',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
        migrations.CreateModel(
            name='OrganizationBusinessType',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('business_type', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_links', to='users.businesstype')),
                ('organization', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_business_types', to='users.organization')),
            ],
            options={
                'verbose_name': 'Organization Business Type',
                'verbose_name_plural': 'Organization Business Types',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='business_types',
            field=models.ManyToManyField(blank=True, related_name='organizations', through='users.OrganizationBusinessType', to='users.businesstype'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='PlanFeature',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddConstraint(
            model_name='organizationbusinesstype',
            constraint=models.UniqueConstraint(fields=('organization', 'business_type'), name='unique_business_type_per_org'),
        ),
        migrations.AddConstraint(
            model_name='organizationbusinesstype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='unique_primary_business_type_per_org'),
        ),
    ]
