# Generated by Django 5.1.12 on 2026-09-20 17:37

from django.db import migrations

from core.applications.users.defaults import BUSINESS_TYPES


def seed_business_types(apps, schema_editor):
    BusinessType = apps.get_model("users", "BusinessType")

    # Only write columns that exist at this point in migration history, so a
    # later migration that adds a field to BusinessType can't break this one on
    # a fresh database.
    columns = {field.name for field in BusinessType._meta.get_fields()}

    for entry in BUSINESS_TYPES:
        values = {key: value for key, value in entry.items() if key in columns and key != "code"}
        BusinessType.objects.update_or_create(code=entry["code"], defaults=values)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_businesstype_remove_planfeature_feature_and_more'),
    ]

    operations = [
        # Reverse is a no-op: organizations may reference these rows (PROTECT).
        migrations.RunPython(seed_business_types, migrations.RunPython.noop),
    ]