# Generated by Django 5.1.12 on 2026-09-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seed_business_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text="ISO 3166-2 subdivision code, e.g. 'NG-AB'.", max_length=10)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
