# Generated by Django 5.1.12 on 2026-09-27 22:25

from django.db import migrations

NG_STATES = [
    ("Abia", "NG-AB"), ("Adamawa", "NG-AD"), ("Akwa Ibom", "NG-AK"),
    ("Anambra", "NG-AN"), ("Bauchi", "NG-BA"), ("Bayelsa", "NG-BY"),
    ("Benue", "NG-BE"), ("Borno", "NG-BO"), ("Cross River", "NG-CR"),
    ("Delta", "NG-DE"), ("Ebonyi", "NG-EB"), ("Edo", "NG-ED"),
    ("Ekiti", "NG-EK"), ("Enugu", "NG-EN"), ("Federal Capital Territory", "NG-FC"),
    ("Gombe", "NG-GO"), ("Imo", "NG-IM"), ("Jigawa", "NG-JI"),
    ("Kaduna", "NG-KD"), ("Kano", "NG-KN"), ("Katsina", "NG-KT"),
    ("Kebbi", "NG-KE"), ("Kogi", "NG-KO"), ("Kwara", "NG-KW"),
    ("Lagos", "NG-LA"), ("Nasarawa", "NG-NA"), ("Niger", "NG-NI"),
    ("Ogun", "NG-OG"), ("Ondo", "NG-ON"), ("Osun", "NG-OS"),
    ("Oyo", "NG-OY"), ("Plateau", "NG-PL"), ("Rivers", "NG-RI"),
    ("Sokoto", "NG-SO"), ("Taraba", "NG-TA"), ("Yobe", "NG-YO"),
    ("Zamfara", "NG-ZA"),
]


def seed_ng_states(apps, schema_editor):
    State = apps.get_model("users", "State")
    for name, code in NG_STATES:
        State.objects.get_or_create(country="NG", name=name, defaults={"code": code})


def unseed_ng_states(apps, schema_editor):
    State = apps.get_model("users", "State")
    State.objects.filter(country="NG").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_state'),
    ]

    operations = [
        migrations.RunPython(seed_ng_states, reverse_code=unseed_ng_states),
    ]