# Generated by Django 5.1.12 on 2026-09-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_seed_states_ng'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal/ZIP code'),
        ),
    ]
