# Generated by Django 5.1.12 on 2026-09-15 02:34

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique human-readable identifier (e.g., TRX-2026-0001).', max_length=50, unique=True, verbose_name='Transaction ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('payment_received', 'Payment Received'), ('payment_sent', 'Payment Sent'), ('refund', 'Refund'), ('stock_adjustment', 'Stock Adjustment'), ('stock_transfer', 'Stock Transfer'), ('return', 'Customer Return')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reversed', 'Reversed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('organization', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.organization')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(choices=[('cash_bank', 'Cash / Bank'), ('accounts_receivable', 'Accounts Receivable'), ('accounts_payable', 'Accounts Payable'), ('sales_revenue', 'Sales Revenue'), ('cogs', 'Cost of Goods Sold'), ('inventory_asset', 'Inventory Asset'), ('discounts', 'Discounts Given'), ('tax_payable', 'Tax Payable')], db_index=True, max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Amount debited to the account. Increases Assets/Expenses, decreases Liabilities/Revenue/Equity.', max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Amount credited to the account. Increases Liabilities/Revenue/Equity, decreases Assets/Expenses.', max_digits=15)),
                ('transaction', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_entries', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Financial Ledger Entry',
                'verbose_name_plural': 'Financial Ledger Entries',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
