# Generated by Django 5.1.12 on 2026-10-01 20:03

import core.helper.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=20)),
                ('name', models.CharField(help_text='Individual name or company name.', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Derived/cached outstanding balance; source of truth is payment history.', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['organization', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(choices=[('cash_bank', 'Cash / Bank'), ('accounts_receivable', 'Accounts Receivable'), ('accounts_payable', 'Accounts Payable'), ('sales_revenue', 'Sales Revenue'), ('cogs', 'Cost of Goods Sold'), ('inventory_asset', 'Inventory Asset'), ('discounts', 'Discounts Given'), ('tax_payable', 'Tax Payable')], db_index=True, max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Amount debited to the account. Increases Assets/Expenses, decreases Liabilities/Revenue/Equity.', max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Amount credited to the account. Increases Liabilities/Revenue/Equity, decreases Assets/Expenses.', max_digits=15)),
            ],
            options={
                'verbose_name': 'Financial Ledger Entry',
                'verbose_name_plural': 'Financial Ledger Entries',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique human-readable identifier (e.g., TRX-2026-0001).', max_length=50, unique=True, verbose_name='Transaction ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('payment_received', 'Payment Received'), ('payment_sent', 'Payment Sent'), ('refund', 'Refund'), ('stock_adjustment', 'Stock Adjustment'), ('stock_transfer', 'Stock Transfer'), ('return', 'Customer Return')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reversed', 'Reversed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
