# Generated by Django 5.1.12 on 2026-10-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
