# Generated by Django 5.1.12 on 2026-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('payment_received', 'Payment Received'), ('payment_sent', 'Payment Sent'), ('refund', 'Refund'), ('stock_adjustment', 'Stock Adjustment'), ('stock_transfer', 'Stock Transfer'), ('return', 'Customer Return'), ('opening_stock', 'Opening Stock')], db_index=True, max_length=30),
        ),
    ]
