# Generated by Django 5.2.8 on 2025-12-04 23:12

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='users.school'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='classroom',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='users.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'academic_class', 'arm')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('teacher', 'classroom', 'subject')},
        ),
    ]
