# Generated by Django 5.1.12 on <date>

from django.db import migrations

DEFAULT_PLAN_NAME = "Free"

# Limits are left unset (None = unlimited, per project convention) because they
# are a product decision. Set them in the admin (Plans) when you decide.
DEFAULT_PLAN = {
    "description": "Core features to get your business started.",
    "price": 0,
    "billing_period_days": 30,
    "trial_period_days": 0,
    "is_active": True,
}

FEATURES = [
    {"code": "CUSTOM_TEMPLATES", "name": "Custom document templates",
     "description": "Organization-owned invoice, receipt, quote and credit note templates."},
]


def _values(model, values):
    """Only columns that exist at this point in migration history."""
    columns = {field.name for field in model._meta.get_fields()}
    return {key: value for key, value in values.items() if key in columns}


def seed_default_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Feature = apps.get_model("subscriptions", "Feature")

    # Case-insensitive, matching how the application looks the plan up.
    if not Plan.objects.filter(name__iexact=DEFAULT_PLAN_NAME).exists():
        Plan.objects.create(name=DEFAULT_PLAN_NAME, **_values(Plan, DEFAULT_PLAN))

    for feature in FEATURES:
        Feature.objects.get_or_create(
            code=feature["code"],
            defaults=_values(Feature, {k: v for k, v in feature.items() if k != "code"}),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_default_plan, migrations.RunPython.noop),
    ]