# Generated by Django 5.2.8 on 2025-12-04 23:12

import core.helper.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the session e.g. 2024/2025', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='1st Term, 2nd Term, 3rd Term', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('term_type', models.CharField(choices=[('HALF_TERM', 'Half Term'), ('END_OF_TERM', 'End of Term'), ('FULL_TERM', 'Full Term')], default='FULL_TERM', max_length=20)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentPolicy',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Policy', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('ca_weight', models.PositiveIntegerField(default=40, help_text='Continuous Assessment weight (%)')),
                ('exam_weight', models.PositiveIntegerField(default=60, help_text='Examination weight (%)')),
            ],
            options={
                'verbose_name': 'Assessment Policy',
                'verbose_name_plural': 'Assessment Policies',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(help_text='Test/Exam number e.g. 1 or 2')),
                ('score', models.FloatField(blank=True, null=True)),
                ('date_taken', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assessment Record',
                'verbose_name_plural': 'Assessment Records',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CA', 'Continuous Assessment'), ('EXAM', 'Examination'), ('HALF_TERM', 'Half Term Exam'), ('PROJECT', 'Project'), ('ASSIGNMENT', 'Assignment')], default='CA', max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in reports')),
            ],
            options={
                'verbose_name': 'Assessment Type',
                'verbose_name_plural': 'Assessment Types',
                'ordering': ['policy', 'order', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=3)),
                ('display_name', models.CharField(blank=True, help_text="e.g., A' for honors", max_length=5, null=True)),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('is_honors', models.BooleanField(default=False, help_text="Whether this is an honors grade (A')")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'ordering': ['-max_score'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_ca', models.FloatField(default=0)),
                ('exam_score', models.FloatField(default=0)),
                ('half_term_score', models.FloatField(default=0, help_text='Score for half-term exams')),
                ('total_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0, help_text='Average score for the subject')),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Subject Result',
                'verbose_name_plural': 'Subject Results',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TargetGrade',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_grade', models.CharField(max_length=3)),
                ('target_point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('current_grade', models.CharField(blank=True, max_length=3, null=True)),
                ('current_point', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Target Grade',
                'verbose_name_plural': 'Target Grades',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('comment_type', models.CharField(choices=[('STRENGTH', 'Strength'), ('WEAKNESS', 'Weakness'), ('GENERAL', 'General'), ('IMPROVEMENT', 'Area for Improvement')], default='GENERAL', max_length=20)),
            ],
            options={
                'verbose_name': 'Teacher Comment',
                'verbose_name_plural': 'Teacher Comments',
                'ordering': ['subject_result', 'comment_type'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TermReportSummary',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('total_points', models.FloatField(default=0)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('target_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conduct_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('principal_comment', models.TextField(blank=True, null=True)),
                ('form_teacher_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Term Report Summary',
                'verbose_name_plural': 'Term Report Summaries',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
