# Generated by Django 5.2.8 on 2025-12-04 23:12

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accessments', '0001_initial'),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='school',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='users.school'),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='session',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='accessments.academicsession'),
        ),
        migrations.AddField(
            model_name='assessmentpolicy',
            name='school',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_policies', to='users.school'),
        ),
        migrations.AddField(
            model_name='assessmentpolicy',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='accessments.academicterm'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='classroom_subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='policy',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='accessments.assessmentpolicy'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='assessment_type',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accessments.assessmenttype'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='school',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='classroom_subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessments.academicterm'),
        ),
        migrations.AddField(
            model_name='targetgrade',
            name='classroom_subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='targetgrade',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='targetgrade',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessments.academicterm'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='subject_result',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_comments', to='accessments.subjectresult'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='teacher',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='class_group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessments.academicterm'),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('session', 'name')},
        ),
        migrations.AddConstraint(
            model_name='assessmentpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'term', 'is_active'), name='unique_active_policy_per_school_term'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentrecord',
            unique_together={('student', 'classroom_subject', 'assessment_type', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('school', 'grade', 'is_honors')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectresult',
            unique_together={('student', 'classroom_subject', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='targetgrade',
            unique_together={('student', 'classroom_subject', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='termreportsummary',
            unique_together={('student', 'term')},
        ),
    ]
